### PR TITLE
only newline-and-indent if the let form has existing bindings

### PR DESCRIPTION
**Pull request by matthew-piziak**
Not sure if this is correct but it makes https://github.com/Wilfred/emacs-refactor/issues/52 go away.

### CODE REVIEW

**Comment by matthew-piziak** [comment]
Ah, is `master` failing at the moment?

**Comment by Wilfred** [comment]
It was! I've just pushed a fix :)

**Comment by matthew-piziak** [comment]
@Wilfred Thanks!

**Comment by Wilfred** [comment]
Merged in 03e6a12, thanks for the PR!

**Pull request closed without merging**
