### PR TITLE
Issue #16: c refactoring falls back to `indent-region' if clang-format unavailable

### PR DESCRIPTION
**Pull request by articuluxe**
Provide a fallback for c-mode refactorings if clang format is not available (either the clang executable or the emacs library).

### CODE REVIEW

**Comment by yangyingchao** [comment]
Looks good.

BTW, maybe  we can make a new  customizable variable like 'emr-c-format-fallback-func', and set it to 'indent-region' by default.

In this way, if someone want to write his own formatter or tools, he can create a function, and customize 'emr-c-format-fallback-func' to that function. It will save us from keep modifying this file (emr-c.el).

What do you think?

**Comment by danrharms** [comment]
That sounds reasonable. I will take a look and update the PR.

**Comment by Compro-Prasad** [comment]
This is PR is old. Is this getting any attention? Looks good from my side.

**Comment by Wilfred** [comment]
Seems reasonable :)

Sorry for the huge delay on this.

**Pull request merged**
